[General]
font=Open Sans
language=fr

[Colors]
active=grey
inactive=darkgrey
key=black
key_border=green
text=white

[Geometry]
control_bar_size=32
height=256
spacing=5
width=1024

[Position]
side=top
x_offset=0
y_offset=50
